[params.profileMode]
    enabled = true
    title = "Vrushabh Donge"
    subtitle = "Bridging advanced ML/control research with real-world energy workflows. Building AI and optimization solutions for grid modernization and reliability."
    imageUrl = "/img/profile.jpg"
    imageTitle = "Vrushabh Donge"
    imageWidth = 160
    imageHeight = 160
    
    [[params.profileMode.buttons]]
      name = "Google Scholar"
      url = "https://scholar.google.com/citations?user=Zb04ci4AAAAJ&hl=en"
    
    [[params.profileMode.buttons]]
      name = "Web of Science"
      url = "https://www.webofscience.com/wos/author/record/AFN-3353-2022" 

    [[params.profileMode.buttons]]
      name = "ORCID"
      url = "https://orcid.org/0000-0002-3165-9852"

    [[params.profileMode.buttons]]
      name = "ResearchGate"
      url = "https://www.researchgate.net/profile/Vrushabh-Donge?ev=hdr_xprf"

    [[params.profileMode.buttons]]
      name = "LinkedIn"
      url = "https://www.linkedin.com/in/vrushabh-donge/"

    [[params.profileMode.buttons]]
      name = "GitHub"
      url = "https://github.com/vrushabhd1"

    [[params.profileMode.buttons]]
      name = "Instagram"
      url = "https://www.instagram.com/vrushabhdonge/"

    [[params.profileMode.buttons]]
      name = "CV"
      url = "/files/cv.pdf"
