baseURL = "https://vrushabhd1.github.io/"
languageCode = "en-us"
title = "Vrushabh Donge"
theme = "PaperMod"


[params]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true
  TocOpen = false

  # Makes homepage show your posts list (blog) while allowing intro content
  mainSections = ["posts"]

  [params.profileMode]
    enabled = true
    title = "Vrushabh Donge"
    subtitle = "AI, systems & control, and optimization for grid modernization and power-electronics reliability."
    imageUrl = "/img/profile.jpg"
    imageTitle = "Vrushabh Donge"
    imageWidth = 160
    imageHeight = 160

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
